### ISSUE TITLE
This looks familiar ...

### ISSUE THREAD

**Issue by Hvass-Labs** [asthahariyani/predictingstockreturns#1]
It says that this is your last year's college project. It's funny, because it looks an awful lot like this:

https://github.com/Hvass-Labs/FinanceOps

And this one in particular:

https://github.com/Hvass-Labs/FinanceOps/blob/master/01_Forecasting_Long-Term_Stock_Returns.ipynb

You are very welcome to re-use my research and code, but you should write where you got it from.

**Comment by asthahariyani** [comment]
Hi
It's still a work in progress. Will give the credits. Cheers!
